### ISSUE TITLE
SceneRefactor: Puzzle Fixes

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#433] opened 2024-01-24 06:48 UTC
- [ ] During puzzles you don't fail on chain puzzles
- [ ] should also test clear puzzles
- [ ] test move puzzles
- [ ] Also can't reset without crashing

**Comment by Endaris** [comment] 2024-04-20 18:10
Couldn't reproduce most of these, likely due to earlier changes I don't remember right now.
Remaining puzzle issues should be fixed with https://github.com/Endaris/panel-attack/commit/1fadbdb4033f9c98eefc1a778e4a9b7a4b3e3a34

**Closed as completed** 2024-04-21 00:51 UTC
Labels: bug, Client-side, engine
